---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  policyfile: test/fixtures/policies/default.rb
  product_name: chef
  product_version: 14

verifier:
  name: inspec

platforms:
  - name: ubuntu-18.04
  - name: centos-7.7
  - name: windows-2012r2
    driver:
      box: mwrock/Windows2012R2
      gui: false
  - name: windows-2016
    driver:
      box: mwrock/Windows2016
      gui: false
    provisioner:
      install_strategy: always
      product_version: 14


suites:
  - name: default
    attributes:
      consul:
        config: &default-config
          ports:
           dns: 53
           http: 8500
           serf_lan: 8301
           serf_wan: 8302
           server: 8300
          owner: root
          ui: true
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
          acl_master_token: doublesecret
          acl_datacenter: FortMeade
          acl_default_policy: deny
    excludes:
      - windows-2012r2
      - windows-2016

  - name: client
    named_run_list: client
    excludes:
      - windows-2012r2
      - windows-2016

  - name: git
    attributes:
      go:
        version: 1.9
      consul:
        config: *default-config
        installation:
          provider: git
    excludes:
      - windows-2012r2
      - windows-2016

  - name: windows
    attributes:
      consul:
        config: *default-config
    includes:
      - windows-2012r2
      - windows-2016

  - name: windows_client
    named_run_list: client
    includes:
      - windows-2012r2
      - windows-2016
