---
driver:
  name: dokken
  chef_version: latest
  privileged: true
transport:
  name: dokken
provisioner:
  name: dokken
verifier:
  root_path: /opt/verifier
platforms:
  - name: centos-7
    named_run_list: centos
    driver:
      image: centos:7
      platform: rhel
      pid_one_command: /usr/lib/systemd/systemd
      intermediate_instructions:
        - RUN yum -y install lsof which systemd-sysv initscripts sudo
    attributes:
      poise-service:
        consul:
          provider: systemd
  - name: centos-6
    named_run_list: centos
    driver:
      image: centos:6
      platform: rhel
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN yum -y install which initscripts sudo
  - name: ubuntu-16.04
    named_run_list: debian
    driver:
      image: ubuntu:16.04
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo net-tools -y
    attributes:
      poise-service:
        consul:
          provider: systemd
  - name: ubuntu-14.04
    named_run_list: debian
    driver:
      image: ubuntu-upstart:14.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo net-tools -y
    attributes:
      poise-service:
        consul:
          provider: upstart
  - name: ubuntu-12.04
    named_run_list: debian
    driver:
      image: ubuntu-upstart:12.04
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update -y
        - RUN /usr/bin/apt-get install sudo net-tools -y
    attributes:
      poise-service:
        consul:
          provider: upstart
  - name: debian-8
    named_run_list: debian
    driver:
      image: debian:8
      pid_one_command: /bin/systemd
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release sudo net-tools -y
    attributes:
      poise-service:
        consul:
          provider: systemd
  - name: debian-7
    named_run_list: debian
    driver:
      image: debian:7
      pid_one_command: /sbin/init
      intermediate_instructions:
        - RUN /usr/bin/apt-get update
        - RUN /usr/bin/apt-get install lsb-release sudo net-tools -y
suites:
  - name: default
    provisioner:
      policyfile: test/fixtures/policies/default.rb
    attributes:
      consul:
        config: &default-config
          owner: root
          group: consul
          bootstrap: true
          server: true
          datacenter: FortMeade
          encrypt: CGXC2NsXW4AvuB4h5ODYzQ==
  - name: archive
    provisioner:
      policyfile: test/fixtures/policies/default.rb
    attributes:
      consul:
        provider: binary
        options:
          version: 0.7.0
