---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
    attributes:
      golang:
        install_dir: '/usr'
  - name: centos-5.10
    run_list:
      - recipe[yum-repoforge::default]
    attributes:
      golang:
        install_dir: '/usr'

suites:
  - name: default
    run_list:
      - recipe[consul::default]
  - name: ui
    run_list:
      - recipe[consul::default]
      - recipe[consul::ui]
    attributes:
        consul:
           serve_ui: true
