---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-12.04
  - name: ubuntu-14.04
  - name: centos-6.5
  - name: centos-5.10

suites:
  - name: default
    run_list: 
      - recipe[consul::binary_install]
      - recipe[consul]
  - name: binary
    run_list: 
      - recipe[consul::binary_install]
  - name: source
    run_list: 
      - recipe[golang]
      - recipe[consul::source_install]