name 'consul'
maintainer 'Sous Chefs'
maintainer_email 'help@sous-chefs.org'
license 'Apache-2.0'
description 'Application cookbook which installs and configures Consul.'
version '4.0.0'

supports 'centos', '>= 6.4'
supports 'redhat', '>= 6.4'
supports 'ubuntu', '>= 12.04'
supports 'solaris2'
supports 'arch'
supports 'windows'

depends 'build-essential', '>= 5.0.0'
depends 'nssm', '>= 4.0.0'
depends 'golang'
depends 'poise', '~> 2.2'
depends 'poise-archive', '~> 1.3'
depends 'poise-service', '~> 1.4'

source_url 'https://github.com/sous-chefs/consul'
issues_url 'https://github.com/sous-chefs/consul/issues'

chef_version '>= 13.4'
